#! /usr/bin/env python

import json
from urllib2 import urlopen
import sys
from optparse import OptionParser
from tempfile import mkdtemp
import subprocess
import os
from os.path import expandvars

class CmdException(Exception):
    pass

def main():
    parser = OptionParser(usage="""\
[options] [commands]

Commands:

  review NNN            Reviews the pull request NNN
  list                  Lists all open pull requests""")
    parser.add_option("--upload",
            action="store_true", dest="upload",
            default=False, help="Uploads the results into the pull request")
    options, args = parser.parse_args()
    if len(args) == 1:
        arg, = args
        if arg == "list":
            list_pull_requests()
            return
        print "Unknown command"
        sys.exit(1)
    elif len(args) == 2:
        arg1, arg2 = args
        if arg1 == "review":
            review(int(arg2), upload=options.upload)
            return
        print "Unknown command"
        sys.exit(1)
    elif len(args) == 0:
        pass
    else:
        print "Too many arguments"
        sys.exit(1)
    parser.print_help()

def cmd(s, capture=False, ok_exit_code_list=None):
    """
    Executes the command "s".

    It raises an exception if the command fails to run.

    capture ... If True, it captures its output and returns it as a string.
    ok_exit_code_list ... a list of ok exit codes (otherwise cmd() raises an
    exception)
    """
    if ok_exit_code_list is None:
        ok_exit_code_list = [0]
    s = expandvars(s)
    if capture:
        p = subprocess.Popen(s, shell=True, stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT)
        output = p.communicate()[0]
        r = p.returncode
    else:
        output = None
        r = os.system(s)
    if r not in ok_exit_code_list:
        raise CmdException("Command '%s' failed with err=%d." % (s, r))
    return output

def github_get_pull_request_all():
    """
    Returns all github pull requests.
    """
    return json.load(urlopen('http://github.com/api/v2/json/pulls/sympy/sympy'))

def github_get_pull_request(n):
    """
    Returns pull request 'n'.
    """
    url = 'http://github.com/api/v2/json/pulls/sympy/sympy/%d'
    data = json.load(urlopen(url % n))
    return data["pull"]

def list_pull_requests():
    p = github_get_pull_request_all()
    for pull in p['pulls']:
        n = pull['number']
        repo = pull['head']['repository']['url']
        branch = pull['head']['ref']
        print "#%03d: %s %s" % (n, repo, branch)

def review(n, upload=False):
    tmpdir = mkdtemp()
    print "> Working directory: %s" % tmpdir
    pull = github_get_pull_request(n)
    assert pull['number'] == n
    print "> Reviewing pull request #%d" % n
    repo = pull['head']['repository']['url']
    branch = pull['head']['ref']
    user = pull["user"]
    print "> Pull request info:"
    print '>     Author: "%s" <%s>' % (user["name"], user["email"])
    print ">     Repository: %s" % repo
    print ">     Branch: %s" % branch

    open("%s/branches" % tmpdir, "w").write("%s %s" % (repo, branch))
    print "> Cloning sympy/sympy master"
    cmd("cd %s; git clone https://github.com/sympy/sympy.git" % tmpdir)
    print "> Running sympy-next"
    cmd("other/sympy-next.py %s/sympy %s/branches %s/out" % (tmpdir, tmpdir,
        tmpdir))

if __name__ == "__main__":
    main()
