application: sympy-reviews
version: 8
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.py

builtins:
- remote_api: on

libraries:
- name: django
  version: "latest"
